sudo: required
services:
  - docker

 before_install:
   - docker build -t imagetest -f ./client/Dockerfile.dev ./client

script:
  - docker run imagetest npm test -- --coverage

after_success:
  - docker build -t bashthestampede/multi-client ./client
  - docker build -t bashthestampede/multi-nginx ./nginx
  - docker build -t bashthestampede/multi-server ./server
  - docker build -t bashthestampede/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bashthestampede/multi-client
  - docker push bashthestampede/multi-nginx
  - docker push bashthestampede/multi-server
  - docker push bashthestampede/multi-worker
